/**
 * @file error-codes.ts
 * @description Unified internal error codes for client-side consumption.
 * These codes allow frontends to show specific localized messages or trigger UI logic.
 */

export const ERROR_CODES = {
  COMMON: {
    INVALID_INPUT: 'INVALID_INPUT',
    FORBIDDEN: 'FORBIDDEN',
    FORBIDDEN_OWNERSHIP: 'FORBIDDEN_OWNERSHIP',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  },

  AUTH: {
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    MISSING_COOKIE_TOKEN: 'MISSING_COOKIE_TOKEN',
    INVALID_SESSION: 'INVALID_SESSION',
    SESSION_REVOKED: 'SESSION_REVOKED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    PHONE_ALREADY_VERIFIED: 'PHONE_ALREADY_VERIFIED',
    OTP_COOLDOWN: 'OTP_COOLDOWN',
    INVALID_OTP: 'INVALID_OTP',
    EXPIRED_OTP: 'EXPIRED_OTP',
    WRONG_CURRENT_PASSWORD: 'WRONG_CURRENT_PASSWORD',
    PASSWORD_MUST_BE_DIFFERENT: 'PASSWORD_MUST_BE_DIFFERENT',
  },

  RATE_LIMIT: {
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  },

  DATABASE: {
    UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  },

  NOTIFICATION: {
    SEND_EMAIL_FAILED: 'SEND_EMAIL_FAILED',
    SEND_SMS_FAILED: 'SEND_SMS_FAILED',
    SEND_ZALO_FAILED: 'SEND_ZALO_FAILED',
    MISSING_CONFIG: 'MISSING_CONFIG',
    GATEWAY_REJECTED: 'GATEWAY_REJECTED',
  },

  // Future installments:
  // PRODUCT: { PRODUCT_NOT_PUBLISHED: 'PRODUCT_NOT_PUBLISHED' }
} as const;

/**
 * @type ErrorCode
 * @description Automatically extracted type from the ERROR_CODES object.
 * Any code added to the object above is automatically included in this type.
 */

type DeepValue<T> = T extends Record<string, any> ? DeepValue<T[keyof T]> : T;

export type ErrorCode = DeepValue<typeof ERROR_CODES>;
